#!/usr/bin/env bash

# EAS Build Hook: Write google-services.json before build
# Place this file in the project root
# Note: iOS folder is generated by EAS from app.json automatically

set -euo pipefail

# Create the directory if it doesn't exist
mkdir -p android/app

# Write google-services.json from EAS environment variable
if [ -n "${GOOGLE_SERVICES_JSON:-}" ]; then
  echo "${GOOGLE_SERVICES_JSON}" > android/app/google-services.json
  echo "✅ google-services.json created from EAS environment variable"
else
  echo "⚠️  GOOGLE_SERVICES_JSON environment variable not found"
  exit 1
fi

